services:
  # API Java
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: comissoes_db
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password_123
    networks:
      - traefik
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # API Java
  backend:
    image: ${IMAGE_BACKEND}
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/comissoes_db
      - SPRING_DATASOURCE_USERNAME=user_admin
      - SPRING_DATASOURCE_PASSWORD=password_123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${SUB_DOMAIN}.${DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.backend.priority=20"
      # O Java já tem /api no @RequestMapping, então apenas enviamos o tráfego direto:
      - "traefik.http.services.backend.loadbalancer.server.port=8080"

  # Frontend React
  frontend:
    image: ${IMAGE_FRONTEND}
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${SUB_DOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.frontend.priority=10"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

networks:
  traefik:
    external: true